#!/usr/bin/env bash

#
# Move messages that match a query into the specified folder.
#
# Usage: notmuch-refile folder query
#

################################################################################
set -eu
set -o pipefail

################################################################################
search() {
  local output=$1
  shift

  notmuch search \
    --output="$output" \
    --exclude=false "$@"
}

################################################################################
config() {
  notmuch config get "$@"
}

################################################################################
main() {
  if [ "$#" -lt 2 ]; then
    echo >&2 "ERROR: Usage: $(basename "$0") folder query"
    exit 1
  fi

  mail_root=$(config database.path)
  maildir=

  if [ "$1" = "INBOX" ]; then
    maildir="$mail_root"
  else
    maildir="$mail_root/.$1"
  fi

  if [ ! -d "$maildir" ]; then
    mmkdir "$maildir"
  fi

  shift

  message_ids=()
  exclude_tags=()

  readarray -t message_ids < <(search messages "$@")
  readarray -t exclude_tags < <(config search.exclude_tags | sed 's/^/-/')

  for msg in "${message_ids[@]}"; do
    # When moving a message, remove tags that might keep it from being
    # seen in the new folder.  I'm assuming this is safe to do since
    # tagging messages as spam, archived, deleted, etc. causes the
    # post-tag hook script to run, and not this one.
    notmuch tag "${exclude_tags[@]}" -- "$msg"

    # Actually move the message:
    search files "$msg" | mrefile "$maildir"
  done

  # Update the database:
  notmuch new
}

################################################################################
main "$@"
